// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: chatapp.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_chatapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_chatapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_chatapp_proto_rawDescGZIP(), []int{0}
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_chatapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_chatapp_proto_rawDescGZIP(), []int{1}
}

func (x *JoinRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *JoinRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type AvailableRooms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []string               `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableRooms) Reset() {
	*x = AvailableRooms{}
	mi := &file_chatapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableRooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableRooms) ProtoMessage() {}

func (x *AvailableRooms) ProtoReflect() protoreflect.Message {
	mi := &file_chatapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableRooms.ProtoReflect.Descriptor instead.
func (*AvailableRooms) Descriptor() ([]byte, []int) {
	return file_chatapp_proto_rawDescGZIP(), []int{2}
}

func (x *AvailableRooms) GetRooms() []string {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type ChatRoomMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Room          string                 `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	IsJoin        bool                   `protobuf:"varint,4,opt,name=isJoin,proto3" json:"isJoin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoomMessage) Reset() {
	*x = ChatRoomMessage{}
	mi := &file_chatapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoomMessage) ProtoMessage() {}

func (x *ChatRoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chatapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoomMessage.ProtoReflect.Descriptor instead.
func (*ChatRoomMessage) Descriptor() ([]byte, []int) {
	return file_chatapp_proto_rawDescGZIP(), []int{3}
}

func (x *ChatRoomMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatRoomMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatRoomMessage) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *ChatRoomMessage) GetIsJoin() bool {
	if x != nil {
		return x.IsJoin
	}
	return false
}

type PrivateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateMessage) Reset() {
	*x = PrivateMessage{}
	mi := &file_chatapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateMessage) ProtoMessage() {}

func (x *PrivateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chatapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateMessage.ProtoReflect.Descriptor instead.
func (*PrivateMessage) Descriptor() ([]byte, []int) {
	return file_chatapp_proto_rawDescGZIP(), []int{4}
}

func (x *PrivateMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PrivateMessage) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *PrivateMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_chatapp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatapp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_chatapp_proto_rawDescGZIP(), []int{5}
}

func (x *MessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_chatapp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatapp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_chatapp_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *LeaveRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *LeaveRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        string                 `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Room          string                 `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_chatapp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_chatapp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_chatapp_proto_rawDescGZIP(), []int{7}
}

func (x *Update) GetUpdate() string {
	if x != nil {
		return x.Update
	}
	return ""
}

func (x *Update) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Update) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *Update) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_chatapp_proto protoreflect.FileDescriptor

const file_chatapp_proto_rawDesc = "" +
	"\n" +
	"\rchatapp.proto\x12\x04chat\"\a\n" +
	"\x05Empty\"9\n" +
	"\vJoinRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\"&\n" +
	"\x0eAvailableRooms\x12\x14\n" +
	"\x05rooms\x18\x01 \x03(\tR\x05rooms\"o\n" +
	"\x0fChatRoomMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04room\x18\x03 \x01(\tR\x04room\x12\x16\n" +
	"\x06isJoin\x18\x04 \x01(\bR\x06isJoin\"`\n" +
	"\x0ePrivateMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\")\n" +
	"\x0fMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"N\n" +
	"\fLeaveRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"`\n" +
	"\x06Update\x12\x16\n" +
	"\x06update\x18\x01 \x01(\tR\x06update\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x12\n" +
	"\x04room\x18\x03 \x01(\tR\x04room\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type2\xeb\x02\n" +
	"\x04Chat\x12<\n" +
	"\bRoomChat\x12\x15.chat.ChatRoomMessage\x1a\x15.chat.ChatRoomMessage(\x010\x01\x12A\n" +
	"\x12SendPrivateMessage\x12\x14.chat.PrivateMessage\x1a\x15.chat.MessageResponse\x12:\n" +
	"\rLeaveChatRoom\x12\x12.chat.LeaveRequest\x1a\x15.chat.MessageResponse\x124\n" +
	"\bJoinRoom\x12\x11.chat.JoinRequest\x1a\x15.chat.MessageResponse\x128\n" +
	"\x13BroadcastRoomUpdate\x12\x11.chat.JoinRequest\x1a\f.chat.Update0\x01\x126\n" +
	"\x11GetAvailableRooms\x12\v.chat.Empty\x1a\x14.chat.AvailableRoomsB\x1cZ\x1aexample/hello/chatapp/grpcb\x06proto3"

var (
	file_chatapp_proto_rawDescOnce sync.Once
	file_chatapp_proto_rawDescData []byte
)

func file_chatapp_proto_rawDescGZIP() []byte {
	file_chatapp_proto_rawDescOnce.Do(func() {
		file_chatapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatapp_proto_rawDesc), len(file_chatapp_proto_rawDesc)))
	})
	return file_chatapp_proto_rawDescData
}

var file_chatapp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chatapp_proto_goTypes = []any{
	(*Empty)(nil),           // 0: chat.Empty
	(*JoinRequest)(nil),     // 1: chat.JoinRequest
	(*AvailableRooms)(nil),  // 2: chat.AvailableRooms
	(*ChatRoomMessage)(nil), // 3: chat.ChatRoomMessage
	(*PrivateMessage)(nil),  // 4: chat.PrivateMessage
	(*MessageResponse)(nil), // 5: chat.MessageResponse
	(*LeaveRequest)(nil),    // 6: chat.LeaveRequest
	(*Update)(nil),          // 7: chat.Update
}
var file_chatapp_proto_depIdxs = []int32{
	3, // 0: chat.Chat.RoomChat:input_type -> chat.ChatRoomMessage
	4, // 1: chat.Chat.SendPrivateMessage:input_type -> chat.PrivateMessage
	6, // 2: chat.Chat.LeaveChatRoom:input_type -> chat.LeaveRequest
	1, // 3: chat.Chat.JoinRoom:input_type -> chat.JoinRequest
	1, // 4: chat.Chat.BroadcastRoomUpdate:input_type -> chat.JoinRequest
	0, // 5: chat.Chat.GetAvailableRooms:input_type -> chat.Empty
	3, // 6: chat.Chat.RoomChat:output_type -> chat.ChatRoomMessage
	5, // 7: chat.Chat.SendPrivateMessage:output_type -> chat.MessageResponse
	5, // 8: chat.Chat.LeaveChatRoom:output_type -> chat.MessageResponse
	5, // 9: chat.Chat.JoinRoom:output_type -> chat.MessageResponse
	7, // 10: chat.Chat.BroadcastRoomUpdate:output_type -> chat.Update
	2, // 11: chat.Chat.GetAvailableRooms:output_type -> chat.AvailableRooms
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatapp_proto_init() }
func file_chatapp_proto_init() {
	if File_chatapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatapp_proto_rawDesc), len(file_chatapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatapp_proto_goTypes,
		DependencyIndexes: file_chatapp_proto_depIdxs,
		MessageInfos:      file_chatapp_proto_msgTypes,
	}.Build()
	File_chatapp_proto = out.File
	file_chatapp_proto_goTypes = nil
	file_chatapp_proto_depIdxs = nil
}
