// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: grpc/chatapp.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRoomMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Room          string                 `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	IsJoin        bool                   `protobuf:"varint,4,opt,name=isJoin,proto3" json:"isJoin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRoomMessage) Reset() {
	*x = ChatRoomMessage{}
	mi := &file_grpc_chatapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRoomMessage) ProtoMessage() {}

func (x *ChatRoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chatapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRoomMessage.ProtoReflect.Descriptor instead.
func (*ChatRoomMessage) Descriptor() ([]byte, []int) {
	return file_grpc_chatapp_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRoomMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatRoomMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatRoomMessage) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *ChatRoomMessage) GetIsJoin() bool {
	if x != nil {
		return x.IsJoin
	}
	return false
}

type PrivateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateMessage) Reset() {
	*x = PrivateMessage{}
	mi := &file_grpc_chatapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateMessage) ProtoMessage() {}

func (x *PrivateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chatapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateMessage.ProtoReflect.Descriptor instead.
func (*PrivateMessage) Descriptor() ([]byte, []int) {
	return file_grpc_chatapp_proto_rawDescGZIP(), []int{1}
}

func (x *PrivateMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PrivateMessage) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *PrivateMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_grpc_chatapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chatapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_grpc_chatapp_proto_rawDescGZIP(), []int{2}
}

func (x *MessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_grpc_chatapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chatapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_grpc_chatapp_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *LeaveRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

var File_grpc_chatapp_proto protoreflect.FileDescriptor

const file_grpc_chatapp_proto_rawDesc = "" +
	"\n" +
	"\x12grpc/chatapp.proto\x12\x04chat\"o\n" +
	"\x0fChatRoomMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04room\x18\x03 \x01(\tR\x04room\x12\x16\n" +
	"\x06isJoin\x18\x04 \x01(\bR\x06isJoin\"`\n" +
	"\x0ePrivateMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\")\n" +
	"\x0fMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\":\n" +
	"\fLeaveRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room2\xbf\x01\n" +
	"\x04Chat\x12<\n" +
	"\bRoomChat\x12\x15.chat.ChatRoomMessage\x1a\x15.chat.ChatRoomMessage(\x010\x01\x12A\n" +
	"\x12SendPrivateMessage\x12\x14.chat.PrivateMessage\x1a\x15.chat.MessageResponse\x126\n" +
	"\tLeaveRoom\x12\x12.chat.LeaveRequest\x1a\x15.chat.MessageResponseB\x1cZ\x1aexample/hello/chatapp/grpcb\x06proto3"

var (
	file_grpc_chatapp_proto_rawDescOnce sync.Once
	file_grpc_chatapp_proto_rawDescData []byte
)

func file_grpc_chatapp_proto_rawDescGZIP() []byte {
	file_grpc_chatapp_proto_rawDescOnce.Do(func() {
		file_grpc_chatapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_chatapp_proto_rawDesc), len(file_grpc_chatapp_proto_rawDesc)))
	})
	return file_grpc_chatapp_proto_rawDescData
}

var file_grpc_chatapp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_chatapp_proto_goTypes = []any{
	(*ChatRoomMessage)(nil), // 0: chat.ChatRoomMessage
	(*PrivateMessage)(nil),  // 1: chat.PrivateMessage
	(*MessageResponse)(nil), // 2: chat.MessageResponse
	(*LeaveRequest)(nil),    // 3: chat.LeaveRequest
}
var file_grpc_chatapp_proto_depIdxs = []int32{
	0, // 0: chat.Chat.RoomChat:input_type -> chat.ChatRoomMessage
	1, // 1: chat.Chat.SendPrivateMessage:input_type -> chat.PrivateMessage
	3, // 2: chat.Chat.LeaveRoom:input_type -> chat.LeaveRequest
	0, // 3: chat.Chat.RoomChat:output_type -> chat.ChatRoomMessage
	2, // 4: chat.Chat.SendPrivateMessage:output_type -> chat.MessageResponse
	2, // 5: chat.Chat.LeaveRoom:output_type -> chat.MessageResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_chatapp_proto_init() }
func file_grpc_chatapp_proto_init() {
	if File_grpc_chatapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_chatapp_proto_rawDesc), len(file_grpc_chatapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_chatapp_proto_goTypes,
		DependencyIndexes: file_grpc_chatapp_proto_depIdxs,
		MessageInfos:      file_grpc_chatapp_proto_msgTypes,
	}.Build()
	File_grpc_chatapp_proto = out.File
	file_grpc_chatapp_proto_goTypes = nil
	file_grpc_chatapp_proto_depIdxs = nil
}
